general:
  prefix: "&bNewHorizon: "
  prefixError: "&f&c "
  prefixInfo: "&f&b "

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "newhorizon"

levels:
  initialExp: 100              # Expérience pour passer du niveau 1 au 2
  expIncrementPercent: 30     # Pourcentage d'augmentation par niveau
  fishing_exp: 8                # Exp gagné avec la pêche
  break_blocks:
    - "*_LOG": 1
    #Mineraits
    - "COAL_ORE": 1
    - "DEEPSLATE_COAL_ORE": 1
    - "IRON_ORE": 3
    - "DEEPSLATE_IRON_ORE": 3
    - "COPPER_ORE": 1
    - "DEEPSLATE_COPPER_ORE": 1
    - "GOLD_ORE": 7
    - "DEEPSLATE_GOLD_ORE": 7
    - "REDSTONE_ORE": 2
    - "DEEPSLATE_REDSTONE_ORE": 2
    - "EMERALD_ORE": 15
    - "DEEPSLATE_EMERALD_ORE": 10
    - "LAPIS_ORE": 3
    - "DEEPSLATE_LAPIS_ORE": 3
    - "DIAMOND_ORE": 30
    - "DEEPSLATE_DIAMOND_ORE": 20
    - "NETHER_GOLD_ORE": 2
    - "NETHER_QUARTZ_ORE": 1
    - "ANCIENT_DEBRIS": 40
    - "LAPIS_ORE": 2
    - "DEEPSLATE_LAPIS_ORE": 2
    #Agricultures
    - "WHEAT": 2
      age: 7
    - "CARROTS": 2
      age: 7
    - "POTATOES": 2
      age: 7
    - "BEETROOTS": 2
      age: 3
    - "PUMPKIN": 2
    - "MELON": 2
    - "SUGAR_CANE": 1

warps:
  spawn:
    world: "world_resource"
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0
  shop:
    world: "world_resource"
    x: 100
    y: 70
    z: -50
    yaw: 90
    pitch: 0


chat-format: "{prefix}{name}&r: {message}"
group-formats:
  default: "&f[lvl] %newhorizon_level% &7{name}: {message}"
  admin: "&f[lvl] %newhorizon_level% &4{name}: {message}"