general:
    prefix: "&bNewHorizon: "
    prefixError: "&f&c "
    prefixInfo: "&f&b "

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "newhorizon"

leveling:
  initial_exp: 100              # Expérience pour passer du niveau 1 au 2
  exp_increment_percent: 30     # Pourcentage d'augmentation par niveau
  max_level: 100                # Niveau maximal atteignable
  fishing_exp: 8                # Exp gagné avec la pêche

chat-format: "{prefix}{name}&r: {message}"
group-formats:
#  default: "[default] {name}&r: {message}"
#  admin: "[admin] {name}&r: {message}"