general:
  prefix: "&bNewHorizon: "
  prefixError: "&f&c "
  prefixInfo: "&f&b "

levels:
  initialExp: 100              # Expérience pour passer du niveau 1 au 2
  expIncrementPercent: 30      # Pourcentage d'augmentation par niveau
  fish_exp: 10                 # Exp gagné avec la pêche
  breed_exp: 15
  break_blocks:
    - "*_LOG": 1
    #Mineraits
    - "COAL_ORE": 1
    - "DEEPSLATE_COAL_ORE": 1
    - "IRON_ORE": 3
    - "DEEPSLATE_IRON_ORE": 3
    - "COPPER_ORE": 1
    - "DEEPSLATE_COPPER_ORE": 1
    - "GOLD_ORE": 7
    - "DEEPSLATE_GOLD_ORE": 7
    - "REDSTONE_ORE": 2
    - "DEEPSLATE_REDSTONE_ORE": 2
    - "EMERALD_ORE": 15
    - "DEEPSLATE_EMERALD_ORE": 10
    - "LAPIS_ORE": 3
    - "DEEPSLATE_LAPIS_ORE": 3
    - "DIAMOND_ORE": 30
    - "DEEPSLATE_DIAMOND_ORE": 20
    - "NETHER_GOLD_ORE": 2
    - "NETHER_QUARTZ_ORE": 1
    - "ANCIENT_DEBRIS": 40
    - "LAPIS_ORE": 2
    - "DEEPSLATE_LAPIS_ORE": 2
    #Agricultures
    - "WHEAT": 2
      age: 7
    - "CARROTS": 2
      age: 7
    - "POTATOES": 2
      age: 7
    - "BEETROOTS": 2
      age: 3
    - "PUMPKIN": 2
    - "MELON": 2
    - "SUGAR_CANE": 1

  # Expérience pour tuer des mobs
  mob_kill_exp:
    - "zombie": 20
    - "skeleton": 15
    - "creeper": 25
    - "enderman": 50

warps:
  newhorizon:
    world: "world_newhorizon"
    x: 1633.5
    y: 67
    z: 402.5
    yaw: -180
    pitch: 0
  dungeon_normal_skeleton:
    world: "world_dungeons"
    x: 106.5
    y: -49
    z: -1.5
    yaw: 90
    pitch: 0
  pvp:
    world: "world_newhorizon"
    x: 1633.5
    y: 36
    z: 420.5
    yaw: 90
    pitch: 0
  resource:
    world: "world_resource"
    x: 23.5
    y: 79
    z: -40.5
    yaw: 90
    pitch: 0


chat-format: "{prefix}{name}&r: {message}"
group-formats:
  default: "&f[lvl] %newhorizon_level% &7{name}: {message}"
  admin: "&f[lvl] %newhorizon_level% &4{name}: {message}"