general:
    prefix: "&bNewHorizon: "
    prefixError: "&f&c "
    prefixInfo: "&f&b "

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "newhorizon"

levels:
  initialExp: 100              # Expérience pour passer du niveau 1 au 2
  expIncrementPercent: 30     # Pourcentage d'augmentation par niveau
  fishing_exp: 8                # Exp gagné avec la pêche
  break_blocks:
    - "*_LOG": 1
    - "COAL_ORE": 1
    - "WHEAT": 1
      age: 7
      test: 98

chat-format: "{prefix}{name}&r: {message}"
group-formats:
#  default: "[default] {name}&r: {message}"
#  admin: "[admin] {name}&r: {message}"